import "@/styles/globals.css";

import { type Metadata } from "next";
import localFont from "next/font/local";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const circular = localFont({
  src: [
    { path: "../../public/fonts/CircularStd-Book.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/CircularStd-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../public/fonts/CircularStd-Bold.woff2", weight: "700", style: "normal" },
    { path: "../../public/fonts/CircularStd-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-circular",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${circular.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
